### ISSUE TITLE
Leave and join back makes user leave party

### ISSUE THREAD

**Issue by PakshP** [exwundee/PartyChat#11]

**Comment by exwundee** [comment]
I was able to reproduce this. It seems when checking for most values that involves players after they rejoin, it doesn't seem to think it's the same player. Going to replace all instances of Players with Strings and rework a few things I should've done from the beginning.

**Comment by exwundee** [comment]
The issue was what I predicted. The player isn't being detected as the same player when they rejoin, so we get around this by using their name. We also add some getters and setters to make changing this in the future much easier if it ever has to be done. It's spring cleaning I was suppose to do earlier in the plugin's development, but neglected. Any future issues that branch from this issue should be posted in a new thread, but for the most part I believe I have everything working as before.
